# **Làm quen với pytorch**
## INTRODUCTION
PyTorch là một framework được xây dựng dựa trên python cung cấp nền tảng tính toán khoa học phục vụ lĩnh vực Deep learning. Pytorch tập trung vào 2 khả năng chính:

> Một sự thay thế cho bộ thư viện numpy để tận dụng sức mạnh tính toán của GPU.

> Một platform Deep learning phục vụ trong nghiên cứu, mang lại sự linh hoạt và tốc độ.


# **Ma trận**
- Trong pytorch, ma trận(mảng) được gọi là các tensors.
- Ma trận 2 chiều 3 * 3 được gọi là 3 * 3 tensor.


In [2]:
# import pytorch library
import torch

# pytorch array
tensor = torch.Tensor(array)
print("Array Type: {}".format(tensor.type)) # type
print("Array Shape: {}".format(tensor.shape)) # shape
print(tensor)

Array Type: <built-in method type of Tensor object at 0x7ffa653a19d8>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Phân phối là một trong những kĩ thuật được sử dụng nhiều nhất trong coding. Hãy cùng xem cách làm nó trong pytorch.

Hãy cùng so sánh numpy và tensor:

- np.ones() = torch.ones()
- np.random.rand() = torch.rand()



In [4]:
import numpy as np
# numpy ones
print("Numpy {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


Với random:

In [5]:
# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.05638909 0.88132194 0.67155601]
 [0.83509149 0.36023409 0.30113162]]

tensor([[0.0267, 0.4493, 0.7886],
        [0.8308, 0.4960, 0.1764]])


**Toán học cơ bản với pytorch**

* Resize: view()
* a và b là tensor.
* Phép cộng: torch.add(a,b) = a + b
* Phép trừ: a.sub(b) = a - b
* Phép nhân tương ứng từng phần tử: torch.mul(a,b) = a * b
* Phép chia tương ứng từng phần tử: torch.div(a,b) = a / b
* Mean: a.mean()
* Độ lệch tiêu chuẩn (std): a.std()



In [6]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)

# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor)))

# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# Mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# Standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229
